---
#- tasks file for roles/supervise
- name: Mise a jour des depots
  apt:
    update-cache: yes
    cache_valid_time: 3600
  become: yes

- name: Instalation de nagios-nrpe-server
  apt:
    name: nagios-nrpe-server
    state: latest
  become: yes

- name: Instalation du plugin nagios Check mem
    get_url:
      url: https://github.com/whereisaaron/linux-check-mem-nagios-plugin/blob/6b46d9ac1fcd9bc60702086fe8770f50d65d0b8d/check_mem
      dest: /usr/lib/nagios/plugins/
      mode: 0777
      group: nagios
      owner: nagios

- name: creation de l'utilisateur nagios
  user:
    name: nagios
    state: present
    shell: /bin/bash
#        groups: sudo
#        append: yes
    password: "{{ 'nagios' | password_hash('sha512') }}"
  become: yes

- name: configuration de nrpe.cfg par le module developer en python
  auto-nagios-nrpe:
    ip_nagios: '192.168.1.49'
  become: yes

- name: redemarage nagios-nrpe-server
  systemd:
    name: nagios-nrpe-server
    state: restarted
  become: yes
